pipeline{
    agent {
    node {label 'testingEnv'
        customWorkspace '/data/workspace/test_pipeline'}}
    agent{
    node {label 'testingEnv1'
        customWorkspace '/data/workspace/test_pipeline'}
    }

    stages {
        stage('First'){ steps{ echo 'step start' }}
        stage('Second'){steps{ echo 'step 2'}}
    }
}