pipeline{
    agent none
    stages {
        stage('distribute'){
              parallel{
                    stage('166'){
                        when{expression{/*如果测试失败，状态为UNSTABLE*/
                            currentBuild.result == null || currentBuild.result == 'SUCCESS'}}
                        agent{ node {
                                label 'testingEnv'
                                customWorkspace '/data/workspace/'
                                }
                             }
                        steps {
                            echo "Test On 166"
                            sh 'whoami'
                            sh 'pip install -r /data/workspace/requirements.txt'
                        }
                    }
                    stage('165'){
                        agent{node {
                                label 'testingEnv1'
                                customWorkspace '/data/workspace/'
                                }}
                    steps {
                        echo "Test On 165"
                        echo "install package"
                        sh 'whoami'
                        sh 'pip install -r /data/workspace/requirements.txt'
                        }
                    }
               }
        }

        stage('Test'){
            mail(to:'hsuanmeng@pershing.com.tw',
                subject: "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) is waiting for input",
                body: "Please go to ${env.BUILD_URL}."
                )
        }
    }

}
