pipeline{
    agent any
    node {
        git url: 'https://github.com/hsuanmeng/test.git'
    }
    stages {
        stage('Compile Stage'){
           steps{
            sh 'test'
           }
        }

        stage('Testing Stage'){
           steps{
            sh 'Stage test'
           }
        }
    }
}